BFI_ITEM_LI = [
    "(a) Talks a lot",
    "(b) Notices other people’s weak points",
    "(c) Does things carefully and completely",
    "(d) Is sad, depressed",
    "(e) Is original, comes up with new ideas",
    "(f) Keeps their thoughts to themselves",
    "(g) Is helpful and not selfish with others",
    "(h) Can be kind of careless",
    "(i) Is relaxed, handles stress well",
    "(j) Is curious about lots of different things",
    "(k) Has a lot of energy",
    "(l) Starts arguments with others",
    "(m) Is a good, hard worker",
    "(n) Can be tense; not always easy going",
    "(o) Clever; thinks a lot",
    "(p) Makes things exciting",
    "(q) Forgives others easily",
    "(r) Isn’t very organized",
    "(s) Worries a lot",
    "(t) Has a good, active imagination",
    "(u) Tends to be quiet",
    "(v) Usually trusts people",
    "(w) Tends to be lazy",
    "(x) Doesn’t get upset easily; steady",
    "(y) Is creative and inventive",
    "(z) Has a good, strong personality",
    "(aa) Can be cold and distant with others",
    "(ab) Keeps working until things are done",
    "(ac) Can be moody",
    "(ad) Likes artistic and creative experiences",
    "(ae) Is kind of shy",
    "(af) Kind and considerate to almost everyone",
    "(ag) Does things quickly and carefully",
    "(ah) Stays calm in difficult situations",
    "(ai) Likes work that is the same every time",
    "(aj) Is outgoing; likes to be with people",
    "(ak) Is sometimes rude to others",
    "(al) Makes plans and sticks to them",
    "(am) Get nervous easily",
    "(an) Likes to think and play with ideas",
    "(ao) Doesn’t like artistic things (plays, music)",
    "(ap) Likes to cooperate; goes along with others",
    "(aq) Has trouble paying attention",
    "(ar) Knows a lot about art, music and books",
]

BFI_traits = [
    "Extraversion",
    "Agreeableness",
    "Conscientiousness",
    "Neuroticism",
    "Openness",
    "Extraversion",
    "Agreeableness",
    "Conscientiousness",
    "Neuroticism",
    "Openness",
    "Extraversion",
    "Agreeableness",
    "Conscientiousness",
    "Neuroticism",
    "Openness",
    "Extraversion",
    "Agreeableness",
    "Conscientiousness",
    "Neuroticism",
    "Openness",
    "Extraversion",
    "Agreeableness",
    "Conscientiousness",
    "Neuroticism",
    "Openness",
    "Extraversion",
    "Agreeableness",
    "Conscientiousness",
    "Neuroticism",
    "Openness",
    "Extraversion",
    "Agreeableness",
    "Conscientiousness",
    "Neuroticism",
    "Openness",
    "Extraversion",
    "Agreeableness",
    "Conscientiousness",
    "Neuroticism",
    "Openness",
    "Openness",
    "Agreeableness",
    "Conscientiousness",
    "Openness",
]

TRAITS = [
    "Extraversion",
    "Agreeableness",
    "Conscientiousness",
    "Neuroticism",
    "Openness",
]